version: "3.7"
services:
  db:
    image: postgres:15
    container_name: app_db
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5438
    expose:
      - 5438

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: app_fastapi
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 6342:8000
    depends_on:
      - db
